//priority: 1000

// Items added here will get the 'valid_apiary' tag, and be usable as Apiary multiblock walls
const validApiaryBlocks = [
    'botania:bifrost_pane',
    'botania:bifrost_perm',
    'botania:elf_glass_pane',
    'botania:mana_glass_pane',
    'botania:elf_glass',
    'botania:mana_glass',

    'glassential:glass_dark',
    'glassential:glass_dark_ethereal',
    'glassential:glass_ethereal',
    'glassential:glass_light',
    'glassential:glass_redstone',

    /mcwwindows:/,

    /minecraft:\w+_concrete$/,
    /minecraft:(|\w+)terracotta$/,

    'minecraft:soul_sand',
    '#minecraft:stone_bricks'
];

const honeyVarieties = [
    'resourcefulbees:blaze_honey',
    'resourcefulbees:brass_honey',
    'resourcefulbees:bronze_honey',
    'resourcefulbees:catnip_honey',
    'resourcefulbees:coal_honey',
    'resourcefulbees:constantan_honey',
    'resourcefulbees:diamond_honey',
    'resourcefulbees:electrum_honey',
    'resourcefulbees:emerald_honey',
    'resourcefulbees:enderium_honey',
    'resourcefulbees:glowstone_honey',
    'resourcefulbees:gold_honey',
    'resourcefulbees:honey',
    'resourcefulbees:icy_honey',
    'resourcefulbees:invar_honey',
    'resourcefulbees:iron_honey',
    'resourcefulbees:lapis_honey',
    'resourcefulbees:lumium_honey',
    'resourcefulbees:netherite_honey',
    'resourcefulbees:obsidian_honey',
    'resourcefulbees:rainbow_honey',
    'resourcefulbees:redstone_honey',
    'resourcefulbees:signalum_honey',
    'resourcefulbees:steel_honey',
    'resourcefulbees:water_honey',
    'resourcefulbees:wither_honey'
];

const combVariants = [
    'aluminum',
    'blaze',
    'boobee',
    'brass',
    'bronze',
    'catnip',
    'clay',
    'coal',
    'constantan',
    'copper',
    'creeper',
    'diamond',
    'electrum',
    'emerald',
    'ender',
    'enderium',
    'ghast',
    'glowstone',
    'gold',
    'gravel',
    'icy',
    'invar',
    'iron',
    'lapis',
    'lead',
    'lumium',
    'netherite',
    'nether_quartz',
    'nickel',
    'obsidian',
    'osmium',
    'pigman',
    'redstone',
    'rgbee',
    'sand',
    'signalum',
    'silver',
    'skeleton',
    'slimy',
    'steel',
    'tin',
    'uranium',
    'water',
    'wither',
    'zinc',
    'zombie'
];
