onEvent('fluid.tags', (event) => {
    event
        .get('create:no_infinite_draining')
        .add([
            /tconstruct/,
            /mekanism/,
            /chorus/,
            /essence/,
            /meat/,
            /slime/,
            /bio/,
            /diesel/,
            /ethanol/,
            /gasoline/,
            /kerosene/,
            /lpg/,
            /lubricant/,
            /plastic/,
            /napalm/,
            /potion/,
            /creosote/,
            /honey/,
            /syrup/,
            /tree_oil/,
            /light_oil/,
            /heavy_oil/,
            /fuel/,
            /plantoil/,
            /vegetable_oil/,
            /yeast/
        ]);
});
