onEvent('item.tags', (event) => {
    event
        .get('enigmatica:ladder_planks')
        .add(/_planks$/)
        .remove([
            'botania:livingwood_planks',
            'botania:mossy_livingwood_planks',
            'botania:dreamwood_planks',
            'botania:mossy_dreamwood_planks',
            'betterendforge:lucernia_planks',
            'betterendforge:jellyshroom_planks',
            'betterendforge:umbrella_tree_planks',
            'betterendforge:helix_tree_planks',
            'betterendforge:tenanea_planks',
            'betterendforge:dragon_tree_planks',
            'betterendforge:pythadendron_planks',
            'betterendforge:end_lotus_planks',
            'betterendforge:lacugrove_planks',
            'betterendforge:mossy_glowshroom_planks',
            'eidolon:polished_planks',
            'environmental:wisteria_planks',
            'environmental:cherry_planks',
            'environmental:willow_planks',
            'upgrade_aquatic:river_planks',
            'upgrade_aquatic:driftwood_planks',
            'atmospheric:grimwood_planks',
            'atmospheric:aspen_planks',
            'atmospheric:kousa_planks',
            'atmospheric:yucca_planks',
            'atmospheric:morado_planks',
            'atmospheric:rosewood_planks',
            'minecraft:warped_planks',
            'minecraft:crimson_planks',
            'minecraft:dark_oak_planks',
            'minecraft:acacia_planks',
            'minecraft:jungle_planks',
            'minecraft:birch_planks',
            'minecraft:spruce_planks',
            'minecraft:oak_planks'
        ]);
});
