events.listen('recipes', (event) => {
	event.replaceInput({type: 'minecraft:stonecutting'}, '#forge:stones/marble', '#enigmatica:stonecutter/marble_cutables')
	event.replaceInput({type: 'minecraft:stonecutting'}, '#forge:stones/limestone', '#enigmatica:stonecutter/limestone_cutables')
	event.replaceInput({type: 'minecraft:stonecutting'}, '#forge:stones/jasper', '#enigmatica:stonecutter/jasper_cutables')
	event.replaceInput({type: 'minecraft:stonecutting'}, '#forge:stones/slate', '#enigmatica:stonecutter/slate_cutables')
	event.replaceInput({type: 'minecraft:stonecutting'}, '#forge:stones/basalt', '#enigmatica:stonecutter/basalt_cutables')
	event.replaceInput({type: 'minecraft:stonecutting'}, 'quark:myalite', '#enigmatica:stonecutter/myalite_cutables')
	event.replaceInput({type: 'minecraft:stonecutting'}, 'ars_nouveau:arcane_stone', '#enigmatica:stonecutter/ars_arcane_cutables')

	event.stonecutting('minecraft:stone', 'minecraft:stone_bricks')
	event.stonecutting('minecraft:stone', 'minecraft:chiseled_stone_bricks')
	event.stonecutting('minecraft:stone_bricks', 'minecraft:chiseled_stone_bricks')
	event.stonecutting('minecraft:stone', '#masonry:stone_cutables')
	event.stonecutting('minecraft:stone_bricks', '#masonry:stone_cutables')

	event.remove({id: 'minecraft:polished_granite_from_granite_stonecutting'})
	event.remove({id: 'quark:building/stonecutting/stonevariants/chiseled_granite_bricks_stonecutter'})
	event.remove({id: 'quark:building/stonecutting/stonevariants/granite_bricks_stonecutter'})
	event.remove({id: 'quark:building/stonecutting/stonevariants/granite_pavement_stonecutter'})
	event.remove({id: 'quark:building/stonecutting/stonevariants/granite_pillar_stonecutter'})
	event.remove({type: 'minecraft:stonecutting', input: 'minecraft:granite', mod: 'create'})

	event.stonecutting('minecraft:granite', '#enigmatica:stonecutter/granite_cutables')
	event.stonecutting('minecraft:polished_granite', '#enigmatica:stonecutter/granite_cutables')
	event.stonecutting('minecraft:granite', '#masonry:granite_cutables')
	event.stonecutting('minecraft:polished_granite', '#masonry:granite_cutables')
	event.stonecutting('quark:granite_bricks', '#enigmatica:stonecutter/granite_cutables')
	event.stonecutting('quark:chiseled_granite_bricks', '#enigmatica:stonecutter/granite_cutables')
	event.stonecutting('quark:granite_pavement', '#enigmatica:stonecutter/granite_cutables')
	event.stonecutting('quark:granite_pillar', '#enigmatica:stonecutter/granite_cutables')
	event.stonecutting('create:granite_bricks', '#enigmatica:stonecutter/granite_cutables')
	event.stonecutting('create:granite_pillar', '#enigmatica:stonecutter/granite_cutables')
	event.stonecutting('create:fancy_granite_bricks', '#enigmatica:stonecutter/granite_cutables')
	event.stonecutting('create:paved_granite', '#enigmatica:stonecutter/granite_cutables')
	event.stonecutting('create:layered_granite', '#enigmatica:stonecutter/granite_cutables')
	event.stonecutting('create:mossy_granite', '#enigmatica:stonecutter/granite_cutables')
	event.stonecutting('create:overgrown_granite', '#enigmatica:stonecutter/granite_cutables')
	
	event.remove({id: 'minecraft:polished_diorite_from_diorite_stonecutting'})
	event.remove({id: 'quark:building/stonecutting/stonevariants/chiseled_diorite_bricks_stonecutter'})
	event.remove({id: 'quark:building/stonecutting/stonevariants/diorite_bricks_stonecutter'})
	event.remove({id: 'quark:building/stonecutting/stonevariants/diorite_pavement_stonecutter'})
	event.remove({id: 'quark:building/stonecutting/stonevariants/diorite_pillar_stonecutter'})
	event.remove({type: 'minecraft:stonecutting', input: 'minecraft:diorite', mod: 'create'})
	
	event.stonecutting('minecraft:diorite', '#enigmatica:stonecutter/diorite_cutables')
	event.stonecutting('minecraft:polished_diorite', '#enigmatica:stonecutter/diorite_cutables')
	event.stonecutting('quark:diorite_bricks', '#enigmatica:stonecutter/diorite_cutables')
	event.stonecutting('quark:chiseled_diorite_bricks', '#enigmatica:stonecutter/diorite_cutables')
	event.stonecutting('quark:diorite_pavement', '#enigmatica:stonecutter/diorite_cutables')
	event.stonecutting('quark:diorite_pillar', '#enigmatica:stonecutter/diorite_cutables')
	event.stonecutting('create:diorite_bricks', '#enigmatica:stonecutter/diorite_cutables')
	event.stonecutting('create:diorite_pillar', '#enigmatica:stonecutter/diorite_cutables')
	event.stonecutting('create:fancy_diorite_bricks', '#enigmatica:stonecutter/diorite_cutables')
	event.stonecutting('create:paved_diorite', '#enigmatica:stonecutter/diorite_cutables')
	event.stonecutting('create:layered_diorite', '#enigmatica:stonecutter/diorite_cutables')
	event.stonecutting('create:mossy_diorite', '#enigmatica:stonecutter/diorite_cutables')
	event.stonecutting('create:overgrown_diorite', '#enigmatica:stonecutter/diorite_cutables')
	
	event.remove({id: 'minecraft:polished_andesite_from_andesite_stonecutting'})
	event.remove({id: 'quark:building/stonecutting/stonevariants/chiseled_andesite_bricks_stonecutter'})
	event.remove({id: 'quark:building/stonecutting/stonevariants/andesite_bricks_stonecutter'})
	event.remove({id: 'quark:building/stonecutting/stonevariants/andesite_pavement_stonecutter'})
	event.remove({id: 'quark:building/stonecutting/stonevariants/andesite_pillar_stonecutter'})
	event.remove({type: 'minecraft:stonecutting', input: 'minecraft:andesite', mod: 'create'})
	
	event.stonecutting('minecraft:andesite', '#enigmatica:stonecutter/andesite_cutables')
	event.stonecutting('minecraft:polished_andesite', '#enigmatica:stonecutter/andesite_cutables')
	event.stonecutting('quark:andesite_bricks', '#enigmatica:stonecutter/andesite_cutables')
	event.stonecutting('quark:chiseled_andesite_bricks', '#enigmatica:stonecutter/andesite_cutables')
	event.stonecutting('quark:andesite_pavement', '#enigmatica:stonecutter/andesite_cutables')
	event.stonecutting('quark:andesite_pillar', '#enigmatica:stonecutter/andesite_cutables')
	event.stonecutting('create:andesite_bricks', '#enigmatica:stonecutter/andesite_cutables')
	event.stonecutting('create:andesite_pillar', '#enigmatica:stonecutter/andesite_cutables')
	event.stonecutting('create:fancy_andesite_bricks', '#enigmatica:stonecutter/andesite_cutables')
	event.stonecutting('create:paved_andesite', '#enigmatica:stonecutter/andesite_cutables')
	event.stonecutting('create:layered_andesite', '#enigmatica:stonecutter/andesite_cutables')
	event.stonecutting('create:mossy_andesite', '#enigmatica:stonecutter/andesite_cutables')
	event.stonecutting('create:overgrown_andesite', '#enigmatica:stonecutter/andesite_cutables')
	
	event.stonecutting('quark:marble', 'embellishcraft:marble')
	event.stonecutting('astralsorcery:marble_raw', 'embellishcraft:marble')
	event.stonecutting('quark:marble', 'astralsorcery:marble_raw')
	event.stonecutting('astralsorcery:marble_raw', 'quark:marble')
	event.stonecutting('embellishcraft:marble', 'astralsorcery:marble_raw')
	event.stonecutting('embellishcraft:marble', 'quark:marble')

	event.stonecutting('quark:limestone', 'create:limestone')
	event.stonecutting('create:limestone', 'quark:limestone')
	
	event.stonecutting('byg:scoria_stone', 'create:scoria')
	event.stonecutting('create:scoria', 'byg:scoria_stone')
	
	event.remove({type: 'minecraft:stonecutting', input: 'create:dolomite'})
	event.stonecutting('create:dolomite', '#enigmatica:stonecutter/dolomite_cutables')
	event.stonecutting('create:dolomite_bricks', '#enigmatica:stonecutter/dolomite_cutables')
	event.stonecutting('create:dolomite_pillar', '#enigmatica:stonecutter/dolomite_cutables')
	event.stonecutting('create:fancy_dolomite_bricks', '#enigmatica:stonecutter/dolomite_cutables')
	event.stonecutting('create:paved_dolomite', '#enigmatica:stonecutter/dolomite_cutables')
	event.stonecutting('create:chiseled_dolomite', '#enigmatica:stonecutter/dolomite_cutables')
	event.stonecutting('create:layered_dolomite', '#enigmatica:stonecutter/dolomite_cutables')
	event.stonecutting('create:polished_dolomite', '#enigmatica:stonecutter/dolomite_cutables')
	event.stonecutting('create:mossy_dolomite', '#enigmatica:stonecutter/dolomite_cutables')
	event.stonecutting('create:overgrown_dolomite', '#enigmatica:stonecutter/dolomite_cutables')
	event.stonecutting('create:dolomite_cobblestone', '#enigmatica:stonecutter/dolomite_cutables')

	event.remove({type: 'minecraft:stonecutting', input: 'create:weathered_limestone'})
	event.stonecutting('create:weathered_limestone', '#enigmatica:stonecutter/weathered_limestone_cutables')
	event.stonecutting('create:weathered_limestone_bricks', '#enigmatica:stonecutter/weathered_limestone_cutables')
	event.stonecutting('create:weathered_limestone_pillar', '#enigmatica:stonecutter/weathered_limestone_cutables')
	event.stonecutting('create:fancy_weathered_limestone_bricks', '#enigmatica:stonecutter/weathered_limestone_cutables')
	event.stonecutting('create:paved_weathered_limestone', '#enigmatica:stonecutter/weathered_limestone_cutables')
	event.stonecutting('create:chiseled_weathered_limestone', '#enigmatica:stonecutter/weathered_limestone_cutables')
	event.stonecutting('create:layered_weathered_limestone', '#enigmatica:stonecutter/weathered_limestone_cutables')
	event.stonecutting('create:polished_weathered_limestone', '#enigmatica:stonecutter/weathered_limestone_cutables')
	event.stonecutting('create:mossy_weathered_limestone', '#enigmatica:stonecutter/weathered_limestone_cutables')
	event.stonecutting('create:overgrown_weathered_limestone', '#enigmatica:stonecutter/weathered_limestone_cutables')
	event.stonecutting('create:weathered_limestone_cobblestone', '#enigmatica:stonecutter/weathered_limestone_cutables')
	
	event.remove({type: 'minecraft:stonecutting', input: 'create:gabbro'})
	event.stonecutting('create:gabbro', '#enigmatica:stonecutter/gabbro_cutables')
	event.stonecutting('create:gabbro_bricks', '#enigmatica:stonecutter/gabbro_cutables')
	event.stonecutting('create:gabbro_pillar', '#enigmatica:stonecutter/gabbro_cutables')
	event.stonecutting('create:fancy_gabbro_bricks', '#enigmatica:stonecutter/gabbro_cutables')
	event.stonecutting('create:paved_gabbro', '#enigmatica:stonecutter/gabbro_cutables')
	event.stonecutting('create:chiseled_gabbro', '#enigmatica:stonecutter/gabbro_cutables')
	event.stonecutting('create:layered_gabbro', '#enigmatica:stonecutter/gabbro_cutables')
	event.stonecutting('create:polished_gabbro', '#enigmatica:stonecutter/gabbro_cutables')
	event.stonecutting('create:mossy_gabbro', '#enigmatica:stonecutter/gabbro_cutables')
	event.stonecutting('create:overgrown_gabbro', '#enigmatica:stonecutter/gabbro_cutables')
	event.stonecutting('create:gabbro_cobblestone', '#enigmatica:stonecutter/gabbro_cutables')
	
	event.remove({type: 'minecraft:stonecutting', input: 'create:scoria'})
	event.stonecutting('create:scoria', '#enigmatica:stonecutter/scoria_cutables')
	event.stonecutting('create:scoria_bricks', '#enigmatica:stonecutter/scoria_cutables')
	event.stonecutting('create:scoria_pillar', '#enigmatica:stonecutter/scoria_cutables')
	event.stonecutting('create:fancy_scoria_bricks', '#enigmatica:stonecutter/scoria_cutables')
	event.stonecutting('create:paved_scoria', '#enigmatica:stonecutter/scoria_cutables')
	event.stonecutting('create:chiseled_scoria', '#enigmatica:stonecutter/scoria_cutables')
	event.stonecutting('create:layered_scoria', '#enigmatica:stonecutter/scoria_cutables')
	event.stonecutting('create:polished_scoria', '#enigmatica:stonecutter/scoria_cutables')
	event.stonecutting('create:mossy_scoria', '#enigmatica:stonecutter/scoria_cutables')
	event.stonecutting('create:overgrown_scoria', '#enigmatica:stonecutter/scoria_cutables')
	event.stonecutting('create:scoria_cobblestone', '#enigmatica:stonecutter/scoria_cutables')
	
	event.remove({type: 'minecraft:stonecutting', input: 'create:dark_scoria'})
	event.stonecutting('create:dark_scoria', '#enigmatica:stonecutter/dark_scoria_cutables')
	event.stonecutting('create:dark_scoria_bricks', '#enigmatica:stonecutter/dark_scoria_cutables')
	event.stonecutting('create:dark_scoria_pillar', '#enigmatica:stonecutter/dark_scoria_cutables')
	event.stonecutting('create:fancy_dark_scoria_bricks', '#enigmatica:stonecutter/dark_scoria_cutables')
	event.stonecutting('create:paved_dark_scoria', '#enigmatica:stonecutter/dark_scoria_cutables')
	event.stonecutting('create:chiseled_dark_scoria', '#enigmatica:stonecutter/dark_scoria_cutables')
	event.stonecutting('create:layered_dark_scoria', '#enigmatica:stonecutter/dark_scoria_cutables')
	event.stonecutting('create:polished_dark_scoria', '#enigmatica:stonecutter/dark_scoria_cutables')
	event.stonecutting('create:mossy_dark_scoria', '#enigmatica:stonecutter/dark_scoria_cutables')
	event.stonecutting('create:overgrown_dark_scoria', '#enigmatica:stonecutter/dark_scoria_cutables')
	event.stonecutting('create:dark_scoria_cobblestone', '#enigmatica:stonecutter/dark_scoria_cutables')

	event.remove({id: 'byg:polished_soapstone'})
	event.remove({id: 'byg:soapstone_bricks'})
	event.remove({id: 'byg:soapstone_pillar'})
	event.remove({id: 'byg:soapstone_tile'})
	event.stonecutting('byg:soapstone', '#enigmatica:stonecutter/soapstone_cutables')
	event.stonecutting('byg:polished_soapstone', '#enigmatica:stonecutter/soapstone_cutables')
	event.stonecutting('byg:soapstone_bricks', '#enigmatica:stonecutter/soapstone_cutables')
	event.stonecutting('byg:soapstone_pillar', '#enigmatica:stonecutter/soapstone_cutables')
	event.stonecutting('byg:soapstone_tile', '#enigmatica:stonecutter/soapstone_cutables')

	event.remove({id: 'byg:dacite_bricks'})
	event.remove({id: 'byg:dacite_pillar'})
	event.remove({id: 'byg:dacite_tile'})
	event.stonecutting('byg:dacite', '#enigmatica:stonecutter/dacite_cutables')
	event.stonecutting('byg:dacite_bricks', '#enigmatica:stonecutter/dacite_cutables')
	event.stonecutting('byg:dacite_pillar', '#enigmatica:stonecutter/dacite_cutables')
	event.stonecutting('byg:dacite_tile', '#enigmatica:stonecutter/dacite_cutables')
	event.stonecutting('byg:dacite_cobblestone', '#enigmatica:stonecutter/dacite_cutables')

	event.remove({type: 'minecraft:stonecutting', input: 'byg:red_rock'})
	event.remove({type: 'minecraft:stonecutting', input: 'byg:red_rock_bricks'})
	event.remove({type: 'minecraft:stonecutting', input: 'byg:chiseled_red_rock_bricks'})
	event.remove({type: 'minecraft:stonecutting', input: 'byg:cracked_red_rock_bricks'})
	event.remove({type: 'minecraft:stonecutting', input: 'byg:mossy_red_rock_bricks'})
	event.stonecutting('byg:red_rock', '#enigmatica:stonecutter/red_rock_cutables')
	event.stonecutting('byg:red_rock_bricks', '#enigmatica:stonecutter/red_rock_cutables')
	event.stonecutting('byg:mossy_red_rock_bricks', '#enigmatica:stonecutter/red_rock_cutables')
	event.stonecutting('byg:chiseled_red_rock_bricks', '#enigmatica:stonecutter/red_rock_cutables')
	event.stonecutting('byg:cracked_red_rock_bricks', '#enigmatica:stonecutter/red_rock_cutables')
	
	event.stonecutting('2x byg:red_rock_slab', 'byg:red_rock')
	event.stonecutting('byg:red_rock_wall', 'byg:red_rock')
	event.stonecutting('byg:red_rock_stairs', 'byg:red_rock')
	
	event.stonecutting('2x byg:red_rock_brick_slab', 'byg:red_rock_bricks')
	event.stonecutting('byg:red_rock_brick_wall', 'byg:red_rock_bricks')
	event.stonecutting('byg:red_rock_brick_stairs', 'byg:red_rock_bricks')

	event.stonecutting('2x byg:chiseled_red_rock_brick_slab', 'byg:chiseled_red_rock_bricks')
	event.stonecutting('byg:chiseled_red_rock_brick_wall', 'byg:chiseled_red_rock_bricks')
	event.stonecutting('byg:chiseled_red_rock_brick_stairs', 'byg:chiseled_red_rock_bricks')
	
	event.stonecutting('2x byg:cracked_red_rock_brick_slab', 'byg:cracked_red_rock_bricks')
	event.stonecutting('byg:cracked_red_rock_brick_wall', 'byg:cracked_red_rock_bricks')
	event.stonecutting('byg:cracked_red_rock_brick_stairs', 'byg:cracked_red_rock_bricks')
	
	event.stonecutting('2x byg:mossy_red_rock_brick_slab', 'byg:mossy_red_rock_bricks')
	event.stonecutting('byg:mossy_red_rock_brick_wall', 'byg:mossy_red_rock_bricks')
	event.stonecutting('byg:mossy_red_rock_brick_stairs', 'byg:mossy_red_rock_bricks')

	event.remove({id: 'byg:scoria_pillar'})
	event.remove({id: 'byg:scoria_stonebricks'})
	event.stonecutting('byg:scoria_stone', '#enigmatica:stonecutter/byg_scoria_cutables')
	event.stonecutting('byg:scoria_pillar', '#enigmatica:stonecutter/byg_scoria_cutables')
	event.stonecutting('byg:scoria_stonebricks', '#enigmatica:stonecutter/byg_scoria_cutables')
	event.stonecutting('byg:scoria_cobblestone', '#enigmatica:stonecutter/byg_scoria_cutables')
	
	event.stonecutting('minecraft:cobblestone', 'byg:rocky_stone')

	event.stonecutting('quark:soul_sandstone', 'quark:soul_sandstone_bricks')
	event.stonecutting('quark:soul_sandstone', 'quark:chiseled_soul_sandstone')
	event.stonecutting('quark:soul_sandstone', 'quark:cut_soul_sandstone')
	event.stonecutting('quark:cut_soul_sandstone', 'quark:chiseled_soul_sandstone')
	event.stonecutting('quark:soul_sandstone_bricks', 'quark:chiseled_soul_sandstone')
	event.stonecutting('quark:soul_sandstone_bricks', 'quark:cut_soul_sandstone')
	event.stonecutting('quark:chiseled_soul_sandstone', 'quark:soul_sandstone_bricks')
	event.stonecutting('quark:cut_soul_sandstone', 'quark:soul_sandstone_bricks')
	
	event.stonecutting('minecraft:magma_block', 'quark:magma_bricks')
	event.stonecutting('quark:permafrost', 'quark:permafrost_bricks')
	event.stonecutting('quark:midori_block', 'quark:midori_pillar')
	event.stonecutting('quark:midori_pillar', 'quark:midori_block')
	event.stonecutting('quark:elder_prismarine', 'quark:elder_prismarine_bricks')
	event.stonecutting('quark:elder_prismarine_bricks', 'quark:elder_prismarine')
	event.stonecutting('minecraft:cobblestone', 'quark:cobblestone_bricks')
	
	event.stonecutting('minecraft:terracotta', 'quark:shingles')
	event.stonecutting('minecraft:white_terracotta', 'quark:white_shingles')
	event.stonecutting('minecraft:orange_terracotta', 'quark:orange_shingles')
	event.stonecutting('minecraft:magenta_terracotta', 'quark:magenta_shingles')
	event.stonecutting('minecraft:light_blue_terracotta', 'quark:light_blue_shingles')
	event.stonecutting('minecraft:yellow_terracotta', 'quark:yellow_shingles')
	event.stonecutting('minecraft:lime_terracotta', 'quark:lime_shingles')
	event.stonecutting('minecraft:pink_terracotta', 'quark:pink_shingles')
	event.stonecutting('minecraft:gray_terracotta', 'quark:gray_shingles')
	event.stonecutting('minecraft:light_gray_terracotta', 'quark:light_gray_shingles')
	event.stonecutting('minecraft:cyan_terracotta', 'quark:cyan_shingles')
	event.stonecutting('minecraft:purple_terracotta', 'quark:purple_shingles')
	event.stonecutting('minecraft:blue_terracotta', 'quark:blue_shingles')
	event.stonecutting('minecraft:brown_terracotta', 'quark:brown_shingles')
	event.stonecutting('minecraft:green_terracotta', 'quark:green_shingles')
	event.stonecutting('minecraft:red_terracotta', 'quark:red_shingles')
	event.stonecutting('minecraft:black_terracotta', 'quark:black_shingles')
	
	event.stonecutting('minecraft:polished_blackstone', 'minecraft:polished_blackstone_bricks')
	event.stonecutting('minecraft:polished_blackstone', 'minecraft:chiseled_polished_blackstone')
	event.stonecutting('minecraft:polished_blackstone_bricks', 'minecraft:chiseled_polished_blackstone')
	event.stonecutting('minecraft:chiseled_polished_blackstone', 'minecraft:polished_blackstone_bricks')
	
	event.remove({id: 'minecraft:cut_sandstone_from_sandstone_stonecutting'})
	event.remove({id: 'minecraft:chiseled_sandstone_from_sandstone_stonecutting'})
	event.remove({id: 'quark:building/stonecutting/sandstone_bricks_stonecutter'})
	event.remove({id: 'quark:building/stonecutting/sandstone_bricks_cut_stonecutter'})
	
	event.stonecutting('minecraft:sandstone', '#enigmatica:stonecutter/sandstone_cutables')
	event.stonecutting('minecraft:cut_sandstone', '#enigmatica:stonecutter/sandstone_cutables')
	event.stonecutting('minecraft:chiseled_sandstone', '#enigmatica:stonecutter/sandstone_cutables')
	event.stonecutting('quark:sandstone_bricks', '#enigmatica:stonecutter/sandstone_cutables')
	event.stonecutting('embellishcraft:sandstone_bricks', '#enigmatica:stonecutter/sandstone_cutables')
	event.stonecutting('embellishcraft:sandstone_large_bricks', '#enigmatica:stonecutter/sandstone_cutables')
	event.stonecutting('embellishcraft:sandstone_tiles', '#enigmatica:stonecutter/sandstone_cutables')
	event.stonecutting('embellishcraft:sandstone_paving', '#enigmatica:stonecutter/sandstone_cutables')
	event.stonecutting('embellishcraft:sandstone_paving_stones', '#enigmatica:stonecutter/sandstone_cutables')

	event.remove({id: 'minecraft:cut_red_sandstone_from_red_sandstone_stonecutting'})
	event.remove({id: 'minecraft:chiseled_red_sandstone_from_red_sandstone_stonecutting'})
	event.remove({id: 'quark:building/stonecutting/red_sandstone_bricks_stonecutter'})
	event.remove({id: 'quark:building/stonecutting/red_sandstone_bricks_cut_stonecutter'})

	event.stonecutting('minecraft:red_sandstone', '#enigmatica:stonecutter/red_sandstone_cutables')
	event.stonecutting('minecraft:cut_red_sandstone', '#enigmatica:stonecutter/red_sandstone_cutables')
	event.stonecutting('minecraft:chiseled_red_sandstone', '#enigmatica:stonecutter/red_sandstone_cutables')
	event.stonecutting('quark:red_sandstone_bricks', '#enigmatica:stonecutter/red_sandstone_cutables')
	event.stonecutting('embellishcraft:red_sandstone_bricks', '#enigmatica:stonecutter/red_sandstone_cutables')
	event.stonecutting('embellishcraft:red_sandstone_large_bricks', '#enigmatica:stonecutter/red_sandstone_cutables')
	event.stonecutting('embellishcraft:red_sandstone_tiles', '#enigmatica:stonecutter/red_sandstone_cutables')
	event.stonecutting('embellishcraft:red_sandstone_paving', '#enigmatica:stonecutter/red_sandstone_cutables')
	event.stonecutting('embellishcraft:red_sandstone_paving_stones', '#enigmatica:stonecutter/red_sandstone_cutables')
	
	event.stonecutting('minecraft:quartz_block', 'minecraft:quartz_bricks')
	event.stonecutting('minecraft:quartz_pillar', 'minecraft:quartz_bricks')
	event.stonecutting('minecraft:chiseled_quartz_block', 'minecraft:quartz_bricks')
	event.stonecutting('minecraft:quartz_block', 'minecraft:quartz_pillar')
	event.stonecutting('minecraft:quartz_bricks', 'minecraft:quartz_pillar')
	event.stonecutting('minecraft:chiseled_quartz_block', 'minecraft:quartz_pillar')
	event.stonecutting('minecraft:quartz_block', 'minecraft:chiseled_quartz_block')
	event.stonecutting('minecraft:quartz_pillar', 'minecraft:chiseled_quartz_block')
	event.stonecutting('minecraft:quartz_bricks', 'minecraft:chiseled_quartz_block')
	
	event.stonecutting('botania:mana_quartz', 'botania:mana_quartz_pillar')
	event.stonecutting('botania:mana_quartz', 'botania:chiseled_mana_quartz')
	event.stonecutting('botania:mana_quartz_pillar', 'botania:chiseled_mana_quartz')
	event.stonecutting('botania:chiseled_mana_quartz', 'botania:mana_quartz_pillar')
	event.stonecutting('botania:blaze_quartz', 'botania:blaze_quartz_pillar')
	event.stonecutting('botania:blaze_quartz', 'botania:chiseled_blaze_quartz')
	event.stonecutting('botania:blaze_quartz_pillar', 'botania:chiseled_blaze_quartz')
	event.stonecutting('botania:chiseled_blaze_quartz', 'botania:blaze_quartz_pillar')
	event.stonecutting('botania:lavender_quartz', 'botania:lavender_quartz_pillar')
	event.stonecutting('botania:lavender_quartz', 'botania:chiseled_lavender_quartz')
	event.stonecutting('botania:lavender_quartz_pillar', 'botania:chiseled_lavender_quartz')
	event.stonecutting('botania:chiseled_lavender_quartz', 'botania:lavender_quartz_pillar')
	event.stonecutting('botania:red_quartz', 'botania:red_quartz_pillar')
	event.stonecutting('botania:red_quartz', 'botania:chiseled_red_quartz')
	event.stonecutting('botania:red_quartz_pillar', 'botania:chiseled_red_quartz')
	event.stonecutting('botania:chiseled_red_quartz', 'botania:red_quartz_pillar')
	event.stonecutting('botania:elf_quartz', 'botania:elf_quartz_pillar')
	event.stonecutting('botania:elf_quartz', 'botania:chiseled_elf_quartz')
	event.stonecutting('botania:elf_quartz_pillar', 'botania:chiseled_elf_quartz')
	event.stonecutting('botania:chiseled_elf_quartz', 'botania:elf_quartz_pillar')
	event.stonecutting('botania:sunny_quartz', 'botania:sunny_quartz_pillar')
	event.stonecutting('botania:sunny_quartz', 'botania:chiseled_sunny_quartz')
	event.stonecutting('botania:sunny_quartz_pillar', 'botania:chiseled_sunny_quartz')
	event.stonecutting('botania:chiseled_sunny_quartz', 'botania:sunny_quartz_pillar')
	
	event.stonecutting('botania:metamorphic_forest_bricks', 'botania:chiseled_metamorphic_forest_bricks')
	event.stonecutting('botania:metamorphic_plains_bricks', 'botania:chiseled_metamorphic_plains_bricks')
	event.stonecutting('botania:metamorphic_mountain_bricks', 'botania:chiseled_metamorphic_mountain_bricks')
	event.stonecutting('botania:metamorphic_fungal_bricks', 'botania:chiseled_metamorphic_fungal_bricks')
	event.stonecutting('botania:metamorphic_swamp_bricks', 'botania:chiseled_metamorphic_swamp_bricks')
	event.stonecutting('botania:metamorphic_desert_bricks', 'botania:chiseled_metamorphic_desert_bricks')
	event.stonecutting('botania:metamorphic_taiga_bricks', 'botania:chiseled_metamorphic_taiga_bricks')
	event.stonecutting('botania:metamorphic_mesa_bricks', 'botania:chiseled_metamorphic_mesa_bricks')
	
	event.stonecutting('bloodmagic:largebloodstonebrick', 'bloodmagic:bloodstonebrick')
	event.stonecutting('bloodmagic:bloodstonebrick', 'bloodmagic:largebloodstonebrick')
	
	event.stonecutting('pneumaticcraft:reinforced_bricks', '#enigmatica:stonecutter/pnc_stone_cutables')
	event.stonecutting('pneumaticcraft:reinforced_brick_tile', '#enigmatica:stonecutter/pnc_stone_cutables')
	event.stonecutting('pneumaticcraft:reinforced_brick_pillar', '#enigmatica:stonecutter/pnc_stone_cutables')
	
	event.stonecutting('embellishcraft:basalt_cobblestone', 'embellishcraft:basalt_paving_stones')
	event.stonecutting('embellishcraft:basalt_paving_stones', 'embellishcraft:basalt_cobblestone')
	event.stonecutting('embellishcraft:basalt', '#enigmatica:stonecutter/embellish_basalt_cutables_raw')
	event.stonecutting('embellishcraft:basalt_bricks', '#enigmatica:stonecutter/embellish_basalt_cutables_raw')	
	event.stonecutting('embellishcraft:basalt_large_bricks', '#enigmatica:stonecutter/embellish_basalt_cutables_raw')	
	event.stonecutting('embellishcraft:smooth_basalt', '#enigmatica:stonecutter/embellish_basalt_cutables_smooth')
	event.stonecutting('embellishcraft:polished_basalt', '#enigmatica:stonecutter/embellish_basalt_cutables_smooth')
	event.stonecutting('embellishcraft:basalt_paving', '#enigmatica:stonecutter/embellish_basalt_cutables_smooth')
	event.stonecutting('embellishcraft:basalt_tiles', '#enigmatica:stonecutter/embellish_basalt_cutables_smooth')
	event.stonecutting('embellishcraft:basalt_ornament', '#enigmatica:stonecutter/embellish_basalt_cutables_smooth')	
	
	event.stonecutting('embellishcraft:slate_cobblestone', 'embellishcraft:slate_paving_stones')
	event.stonecutting('embellishcraft:slate_paving_stones', 'embellishcraft:slate_cobblestone')
	event.stonecutting('embellishcraft:slate', '#enigmatica:stonecutter/embellish_slate_cutables_raw')
	event.stonecutting('embellishcraft:slate_bricks', '#enigmatica:stonecutter/embellish_slate_cutables_raw')	
	event.stonecutting('embellishcraft:slate_large_bricks', '#enigmatica:stonecutter/embellish_slate_cutables_raw')	
	event.stonecutting('embellishcraft:smooth_slate', '#enigmatica:stonecutter/embellish_slate_cutables_smooth')
	event.stonecutting('embellishcraft:polished_slate', '#enigmatica:stonecutter/embellish_slate_cutables_smooth')
	event.stonecutting('embellishcraft:slate_paving', '#enigmatica:stonecutter/embellish_slate_cutables_smooth')
	event.stonecutting('embellishcraft:slate_tiles', '#enigmatica:stonecutter/embellish_slate_cutables_smooth')
	event.stonecutting('embellishcraft:slate_ornament', '#enigmatica:stonecutter/embellish_slate_cutables_smooth')
	
	event.stonecutting('embellishcraft:marble_cobblestone', 'embellishcraft:marble_paving_stones')
	event.stonecutting('embellishcraft:marble_paving_stones', 'embellishcraft:marble_cobblestone')
	event.stonecutting('embellishcraft:marble', '#enigmatica:stonecutter/embellish_marble_cutables_raw')
	event.stonecutting('embellishcraft:marble_bricks', '#enigmatica:stonecutter/embellish_marble_cutables_raw')	
	event.stonecutting('embellishcraft:marble_large_bricks', '#enigmatica:stonecutter/embellish_marble_cutables_raw')	
	event.stonecutting('embellishcraft:smooth_marble', '#enigmatica:stonecutter/embellish_marble_cutables_smooth')
	event.stonecutting('embellishcraft:polished_marble', '#enigmatica:stonecutter/embellish_marble_cutables_smooth')
	event.stonecutting('embellishcraft:marble_paving', '#enigmatica:stonecutter/embellish_marble_cutables_smooth')
	event.stonecutting('embellishcraft:marble_tiles', '#enigmatica:stonecutter/embellish_marble_cutables_smooth')
	event.stonecutting('embellishcraft:marble_ornament', '#enigmatica:stonecutter/embellish_marble_cutables_smooth')
	
	event.stonecutting('embellishcraft:gneiss_cobblestone', 'embellishcraft:gneiss_paving_stones')
	event.stonecutting('embellishcraft:gneiss_paving_stones', 'embellishcraft:gneiss_cobblestone')
	event.stonecutting('embellishcraft:gneiss', '#enigmatica:stonecutter/embellish_gneiss_cutables_raw')
	event.stonecutting('embellishcraft:gneiss_bricks', '#enigmatica:stonecutter/embellish_gneiss_cutables_raw')	
	event.stonecutting('embellishcraft:gneiss_large_bricks', '#enigmatica:stonecutter/embellish_gneiss_cutables_raw')	
	event.stonecutting('embellishcraft:smooth_gneiss', '#enigmatica:stonecutter/embellish_gneiss_cutables_smooth')
	event.stonecutting('embellishcraft:polished_gneiss', '#enigmatica:stonecutter/embellish_gneiss_cutables_smooth')
	event.stonecutting('embellishcraft:gneiss_paving', '#enigmatica:stonecutter/embellish_gneiss_cutables_smooth')
	event.stonecutting('embellishcraft:gneiss_tiles', '#enigmatica:stonecutter/embellish_gneiss_cutables_smooth')
	event.stonecutting('embellishcraft:gneiss_ornament', '#enigmatica:stonecutter/embellish_gneiss_cutables_smooth')
	
	event.stonecutting('embellishcraft:jade_cobblestone', 'embellishcraft:jade_paving_stones')
	event.stonecutting('embellishcraft:jade_paving_stones', 'embellishcraft:jade_cobblestone')
	event.stonecutting('embellishcraft:jade', '#enigmatica:stonecutter/embellish_jade_cutables_raw')
	event.stonecutting('embellishcraft:jade_bricks', '#enigmatica:stonecutter/embellish_jade_cutables_raw')	
	event.stonecutting('embellishcraft:jade_large_bricks', '#enigmatica:stonecutter/embellish_jade_cutables_raw')	
	event.stonecutting('embellishcraft:smooth_jade', '#enigmatica:stonecutter/embellish_jade_cutables_smooth')
	event.stonecutting('embellishcraft:polished_jade', '#enigmatica:stonecutter/embellish_jade_cutables_smooth')
	event.stonecutting('embellishcraft:jade_paving', '#enigmatica:stonecutter/embellish_jade_cutables_smooth')
	event.stonecutting('embellishcraft:jade_tiles', '#enigmatica:stonecutter/embellish_jade_cutables_smooth')
	event.stonecutting('embellishcraft:jade_ornament', '#enigmatica:stonecutter/embellish_jade_cutables_smooth')
	
	event.stonecutting('embellishcraft:larvikite_cobblestone', 'embellishcraft:larvikite_paving_stones')
	event.stonecutting('embellishcraft:larvikite_paving_stones', 'embellishcraft:larvikite_cobblestone')
	event.stonecutting('embellishcraft:larvikite', '#enigmatica:stonecutter/embellish_larvikite_cutables_raw')
	event.stonecutting('embellishcraft:larvikite_bricks', '#enigmatica:stonecutter/embellish_larvikite_cutables_raw')	
	event.stonecutting('embellishcraft:larvikite_large_bricks', '#enigmatica:stonecutter/embellish_larvikite_cutables_raw')	
	event.stonecutting('embellishcraft:smooth_larvikite', '#enigmatica:stonecutter/embellish_larvikite_cutables_smooth')
	event.stonecutting('embellishcraft:polished_larvikite', '#enigmatica:stonecutter/embellish_larvikite_cutables_smooth')
	event.stonecutting('embellishcraft:larvikite_paving', '#enigmatica:stonecutter/embellish_larvikite_cutables_smooth')
	event.stonecutting('embellishcraft:larvikite_tiles', '#enigmatica:stonecutter/embellish_larvikite_cutables_smooth')
	event.stonecutting('embellishcraft:larvikite_ornament', '#enigmatica:stonecutter/embellish_larvikite_cutables_smooth')
	
});