events.listen('item.tags', (event) => {
    event
        .get('minecraft:wooden_buttons')
        .add([
            'byg:aspen_button',
            'byg:baobab_button',
            'byg:blue_enchanted_button',
            'byg:cherry_button',
            'byg:cika_button',
            'byg:cypress_button',
            'byg:ebony_button',
            'byg:fir_button',
            'byg:green_enchanted_button',
            'byg:holly_button',
            'byg:jacaranda_button',
            'byg:mahogany_button',
            'byg:mangrove_button',
            'byg:maple_button',
            'byg:pine_button',
            'byg:rainbow_eucalyptus_button',
            'byg:redwood_button',
            'byg:skyris_button',
            'byg:willow_button',
            'byg:witch_hazel_button',
            'byg:zelkova_button',
            'byg:sythian_button',
            'byg:embur_button',
            'byg:palm_button',
            'byg:lament_button',
            'byg:ether_button',
            'byg:bulbis_button',
            'byg:nightshade_button'
        ]);
});
